yname: opensarlab_lib
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - pip
  - ipywidgets
  - jupyter
  - kernda
  - ipython
  - jupyterthemes
  - numpy
  - pandas
  - matplotlib
  - gdal
  - pyproj
  - pip:
    - hyp3-sdk~=1.0
    - asf_hyp3


